# fly.toml app configuration file generated for medimate-api on 2025-08-08T22:58:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medimate-api'
primary_region = 'sjc'

[build]

[env]
  PYTHONPATH = '/app'
  QDRANT_MODE = 'cloud'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    
  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  grace_period = "5s"
  interval = "15s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "2s"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
