# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "veramate-api"
primary_region = "sjc"  # San Jose, change to your preferred region

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  PYTHONPATH = "/app"
  QDRANT_MODE = "cloud"

# Add your secrets with: fly secrets set KEY=value
# fly secrets set QDRANT_URL=your_url
# fly secrets set QDRANT_API_KEY=your_key
# fly secrets set R2_ACCOUNT_ID=your_id
# fly secrets set R2_ACCESS_KEY_ID=your_key
# fly secrets set R2_SECRET_ACCESS_KEY=your_secret
# fly secrets set R2_BUCKET_NAME=your_bucket
# fly secrets set OPENAI_API_KEY=your_key
# fly secrets set LANGCHAIN_API_KEY=your_key