name: Keep API Warm

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Health Check
        run: |
          curl -f https://veramate-api.onrender.com/health || exit 0
          echo "API pinged at $(date)"
      
      # Optional: Add more detailed health check
      - name: Check API Status
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://veramate-api.onrender.com/health)
          if [ $response -eq 200 ]; then
            echo "✅ API is healthy (HTTP $response)"
          else
            echo "⚠️ API returned HTTP $response"
          fi